PROJECT_FILEPATH = "/home/brandon/Documents/python-projects/simple-home-theater"
MEDIA_PLAYER = "mpv"
DEPLOYMENT_TYPE = "CLI"
# DEPLOYMENT_TYPE = "WEB"
APP_NAME = "Simple Home Theater"
AUTOPLAY_COUNTDOWN = 30
USER_TABLE = "/data/users.csv"
CATEGORY_TABLE = "/data/categories.csv"
CONTENT_TABLE = "/data/contents.csv"
